### ISSUE TITLE
throttler.py raising TypeError: bad operand type for unary +: 'str'

### ISSUE THREAD

**Issue by billrideout** [robert-kisteleki/django-email-throttler#3]
line 116 in throttler.py has two unwanted plus signs:

cls.tmpdir_name, cls.file_prefix, + str(bb), + "^" +

This gave me the error:
TypeError: bad operand type for unary +: 'str'

With this change it worked fine:
cls.tmpdir_name, cls.file_prefix, str(bb),  "^" +

**Comment by robert-kisteleki** [comment]
Thanks for pointing this out! It crept in in the last PR, not sure why though. Your suggestion is syntactically correct but the meaning is to join a path and a filename so '+' is better
