### ISSUE TITLE
Document changes to INSTALLED_APPS 

### ISSUE THREAD

**Issue by DrKentB** [robert-kisteleki/django-email-throttler#5]
I love your django-email-throttler. I did struggle a bit with some missing info in the INSTALLATION INSTRUCTIONS. First was that the pip install resulted in a package named "django_email_throttler" and the other which was couple to the first was that I needed to add 'django_email_throttler' to the INSTALLED_APPS in the django settings file, e.g.,

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_email_throttler',           <---
]

Might save others some time to capture this in the instructions. Thanks!

**Comment by robert-kisteleki** [comment]
Fair observations, thank you for pointing them out! I updated the README accordingly.
